# Generated by Django 2.2.12 on 2020-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200716_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='icone',
        ),
        migrations.AlterField(
            model_name='reseau',
            name='icones',
            field=models.CharField(choices=[('fa fa-facebook', 'facebook'), ('fa fa-instagram', 'instagram'), ('fa fa-twitter', 'twitter'), ('fa fa-pinterest', 'pinterest'), ('fa fa-linkedin', 'linkedin')], max_length=255),
        ),
    ]
