# Generated by Django 2.2.12 on 2020-07-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200716_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseau',
            options={'verbose_name': 'Reseau', 'verbose_name_plural': 'Reseaux'},
        ),
    ]
