# Generated by Django 2.2.12 on 2020-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200716_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='partenaire',
            field=models.ImageField(null='True', upload_to='image/partenaires'),
            preserve_default='True',
        ),
    ]
