# Generated by Django 2.2.12 on 2020-07-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_siteinfo_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseau',
            name='icones',
            field=models.CharField(choices=[('fa fa-facebook', 'facebook'), ('fa fa-instagram', 'instagram'), ('fa fa-twitter', 'twitter'), ('fa fa-pinterest', 'pinterest'), ('fa fa-linkedin', 'linkedin'), ('fa fa-google-plus', 'google-plus'), ('fa fa-envelope', 'envelope')], max_length=255),
        ),
    ]
