# Generated by Django 2.2.12 on 2020-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiapp', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
