# Generated by Django 2.2.12 on 2020-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiapp', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_add',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_update',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
