# Generated by Django 2.2.12 on 2020-07-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organiapp', '0006_auto_20200717_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='produit',
        ),
        migrations.AddField(
            model_name='product',
            name='produit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_product', to='organiapp.Article'),
        ),
    ]
