# Generated by Django 2.2.12 on 2020-07-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiapp', '0007_auto_20200717_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Promotion',
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
    ]
