# Generated by Django 2.2.12 on 2020-07-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiapp', '0010_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='contry',
            new_name='country',
        ),
    ]
