# Generated by Django 2.2.12 on 2020-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiapp', '0011_auto_20200720_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='country_state',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
