# Generated by Django 2.2.12 on 2020-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='methode',
            field=models.TextField(null=True),
        ),
    ]
