# Generated by Django 2.2.12 on 2020-07-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recette_methode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
