# Generated by Django 2.2.12 on 2020-07-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recette_categorie', to='blog.Categorie'),
        ),
        migrations.AddField(
            model_name='recette',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='recette',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_recette', to='blog.Type'),
        ),
    ]
