# Generated by Django 2.2.12 on 2020-07-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200721_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
