# Generated by Django 2.2.12 on 2020-07-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200721_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='types',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
