# Generated by Django 2.2.12 on 2020-07-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200721_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
